- hosts: all
  gather_facts: yes
  serial: "50%"
  become: true
  tasks:
    - name: Update OS (RedHat, CentOS)
      yum: name=*
           state=latest
           update_cache=yes
      when: ansible_os_family == "RedHat"

    - name: Add Docker repository docker-ce-stable
      yum_repository:
        name: Docker CE Stable - $basearch
        description: Docker CE Stable
        file: docker.repo
        baseurl: https://download.docker.com/linux/centos/7/$basearch/stable
        gpgcheck: no
      when: ansible_os_family == "RedHat"

    - name: install the latest version of Docker
      yum:
        name: docker
        state: latest